### ISSUE TITLE
Data Section: encode data header to write 0x00?

### ISSUE THREAD

**Issue by 1046102779** [tetratelabs/wabin#5]
WebAssembly 2.0 Data Section spec: https://www.w3.org/TR/wasm-core-2/binary/modules.html#data-section

```WebAssembly Spec
                 datasec ::= seg*:section11(vec(data))      => seg
                 data    ::= 0x00 e:expr b*:vec(byte)       => {init b*, mode active{memory 0, offset e}}
                          |  0x01  b*:vec(byte)             => {init b*, mode passive}
                          |  0x02  x:memidx e:expr b*:vec(byte) => {init b*, mode active {memory x, offset e}}
```

Encode data writes 0x00 bytecode to `data` header.

Why is there no distinction between `0x00` and `0x02` here? If expression exists, it may be `0x00` or `0x02`; if it does not exist, it must be `0x01`.

https://github.com/tetratelabs/wazero/blob/main/internal/wasm/binary/data.go#L83
```golang
func encodeDataSegment(d *wasm.DataSegment) (ret []byte) {
	// Currently multiple memories are not supported.
	ret = append(ret, leb128.EncodeInt32(0)...)
	ret = append(ret, encodeConstantExpression(d.OffsetExpression)...)
	ret = append(ret, leb128.EncodeUint32(uint32(len(d.Init)))...)
	ret = append(ret, d.Init...)
	return
}
```

**Comment by evacchi** [comment]
hey @1046102779 

indeed we should make a distinction between 0x0 and 0x1; i.e. if `OffsetExpression` is nil, we may assume the mode to be passive and use `0x1`

While for 0x2 I don't know if it's worth supporting at this time. If I understand the spec right, 0x2 is only for the cases where the memory index is >=0, i.e. even though 0 is a valid value, it only makes sense to use when it is >0; however, the spec also says:

> In the current version of WebAssembly, at most one memory may be defined or imported in a single module, so all valid [active](https://www.w3.org/TR/wasm-core-2/syntax/modules.html#syntax-data) data segments have a `memory` value of 0.

If I were to add support for arbitrary memory indices, then I would have to add a field to `wasm.DataSegment` to indicate the memory index and then possibly return an `error` when it's >0; which in turn requires a change of signature in `encodeDataSegment`.

So, for the time being, I would only do the simple thing and correctly encode passive segments as 0x1, otherwise defaulting to 0x0

sounds good?

**Comment by 1046102779** [comment]
Agree.
